version: '3.7'
services: 
    apiservice:
        container_name: webapi
        build: 
            context: ./HealthCheck
            dockerfile: Dockerfile
        ports: 
          - "5000:80"
    uiservice:
        container_name: webapp
        build: 
            context: ./HealthCheckApp
            dockerfile: Dockerfile
        ports: 
          - "4200:80"
        depends_on: 
          - apiservice